FROM eclipse-mosquitto:2.0.14

COPY mosquitto.conf /mosquitto/config/mosquitto.conf

#Run Commands
# cd mqtt_broker
# docker build -t mqtt-broker .
# docker run -d --name mqtt-broker-container mqtt-broker
